-- https://www.hackerrank.com/challenges/weather-observation-station-20/problem

WITH ORDERLIST AS(SELECT LAT_N, ROW_NUMBER() OVER (ORDER BY LAT_N) AS ROWASC, ROW_NUMBER() OVER (ORDER BY LAT_N DESC) AS ROWDESC FROM STATION),
MEDIANS AS(SELECT LAT_N FROM ORDERLIST WHERE ROWASC=ROWDESC OR ROWASC +1 = ROWDESC)
SELECT ROUND (AVG(LAT_N * 1.0),4)AS MEDIAN FROM MEDIANS;